---
- name: My first playbook
  hosts: localhost

  tasks:
  - name: deploy software aptitude repository
    apt:
     name: bastet
     state: present
    become: yes 
    register: results

  - name: print to the screen out results variable
    debug: 
     var: results   
